name: Release deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - '*'

jobs:
  build:
    # Job name is Greeting
    name: Building
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - id: image_build
        uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: kalaxia/v2-api
          registry: docker.io
          buildArgs: FEATURES=ssl-secure
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & push Latest tag
        run: docker tag kalaxia/v2-api:${{ steps.image_build.outputs.tag }} kalaxia/v2-api:latest && docker push kalaxia/v2-api:latest