name: Release deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - '*'

jobs:
  build:
    # Job name is Greeting
    name: Building
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          # if you unshallow in a separate step, use the following option:
          # skip-unshallow: 'true'

      - id: image_build
        uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: kalaxia/api-v2
          registry: docker.io
          buildArgs: FEATURES=ssl-secure,VERSION=${{steps.tagger.outputs.tag}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag & push Latest tag
        run: docker tag kalaxia/api-v2:${{ steps.image_build.outputs.tag }} kalaxia/api-v2:latest && docker push kalaxia/api-v2:latest
